# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5efe2606979f4ccc34b1762e2bae871"
name = "Annon Wish Bucket"
handle = "add-to-wishlist-4"
application_url = "https://add-to-wishlist.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "my-custom-test-store-1.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://add-to-wishlist.vercel.app/auth/callback",
  "https://add-to-wishlist.vercel.app/auth/shopify/callback",
  "https://add-to-wishlist.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://add-to-wishlist.vercel.app/api"
subpath = "myapp"
prefix = "apps"

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
